export const articleConstants = {
  GET_ARTICLES_REQUEST: 'GET_ARTICLES_REQUEST',
  GET_TOP_ARTICLES: 'GET_TOP_ARTICLES',
  GET_SEARCHED_ARTICLES: 'GET_SEARCHED_ARTICLES',
  GET_SELECTED_ARTICLE: 'GET_SELECTED_ARTICLE',
  SHOW_ARTICLE_FULL_VIEW: 'SHOW_ARTICLE_FULL_VIEW',
  CLOSE_ARTICLE_FULL_VIEW: 'CLOSE_ARTICLE_FULL_VIEW'
};
