export const articleConstants = {
  GET_ARTICLES_REQUEST: 'GET_ARTICLES_REQUEST',
  GET_TOP_ARTICLES: 'GET_TOP_ARTICLES',
  GET_SEARCHED_ARTICLES: 'GET_SEARCHED_ARTICLES',
  GET_SELECTED_ARTICLE: 'GET_SELECTED_ARTICLE'
};
