export const userConstants = {
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_ERROR: 'USER_LOGIN_ERROR',
  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_CANCEL_UPDATE_REQUEST: 'USER_CANCEL_UPDATE_REQUEST',
  USER_UPDATE_INFO_SUCCESS: 'USER_UPDATE_INFO_SUCCESS',
  LOGOUT: 'USER_LOGOUT'
};
